<a href="https://colab.research.google.com/github/anshIITK/ml_assgn/blob/main/ML_Assgn_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import numpy as np
from sklearn.datasets import load_svmlight_file
from sklearn.datasets import dump_svmlight_file
from scipy import sparse as sps
from sklearn import model_selection
def loadData( filename, dictSize = 225 ):
	X, y = load_svmlight_file( filename, multilabel = False, n_features = dictSize, offset = 1 )
	return (X, y)

In [70]:
dictSize = 225
(X, y) = loadData( "train", dictSize = dictSize )

In [71]:
X = X.toarray()

In [72]:
X

array([[0., 0., 2., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [73]:
y

array([ 1.,  2.,  4., ...,  2., 32.,  3.])

In [74]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X,y, test_size=0.3)

In [75]:
X_train.shape

(7000, 225)

In [76]:
y_train.shape

(7000,)

In [86]:
#Logistic Regresion
from sklearn.linear_model import LogisticRegression
obj = LogisticRegression(random_state=0, multi_class= 'ovr', solver='liblinear')
obj.fit(X_train, y_train)
obj.predict(X_test)
obj.predict_proba(X_test)



array([[7.98942395e-03, 8.67341040e-01, 1.08367063e-02, ...,
        9.74774500e-04, 8.43665271e-04, 2.30507376e-04],
       [6.42971075e-01, 1.58203730e-04, 3.00886483e-01, ...,
        8.22479551e-04, 1.81962275e-04, 1.55299621e-04],
       [7.98942395e-03, 8.67341040e-01, 1.08367063e-02, ...,
        9.74774500e-04, 8.43665271e-04, 2.30507376e-04],
       ...,
       [1.05686744e-02, 9.00538582e-02, 6.78950309e-03, ...,
        1.02933989e-04, 1.54467401e-03, 1.78033508e-04],
       [1.82789830e-01, 7.22508502e-01, 1.73350956e-03, ...,
        2.08830391e-03, 3.00744687e-03, 1.65023694e-04],
       [8.56698641e-03, 1.16553161e-01, 4.56679933e-03, ...,
        1.09474397e-03, 4.96880454e-04, 3.74412777e-04]])

In [87]:
obj.score(X_test, y_test)

0.7803333333333333

In [83]:
print(obj.coef_)

[[ 9.27553040e-01 -1.68715352e+00  1.09175691e+00 ... -2.80849282e-01
  -4.89615601e-01 -1.23988175e+00]
 [-6.27294801e-01 -5.95163010e-01  2.46172238e-01 ... -1.02607954e-01
  -2.99904783e+00  7.81313005e-01]
 [ 8.82676637e-02  1.33614922e-01 -8.19938809e-01 ... -2.95097595e-01
   9.67715158e-02 -2.80694697e-01]
 ...
 [-2.08772026e-02 -2.31716030e-01 -8.52132665e-02 ... -1.43702517e-02
  -1.84156037e-01  1.42077333e-01]
 [-1.73145823e-01 -4.33365054e-01 -2.53360540e-01 ... -1.00866546e-03
  -1.88095090e-01  5.79376324e-01]
 [-6.37395491e-02 -3.19710886e-01 -1.31459640e+00 ... -2.58560866e-02
  -1.99554948e-01  2.40897720e-02]]


In [99]:
#Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
dtree_model = DecisionTreeClassifier(max_depth=25)
dtree_model.fit(X_train,y_train)
dtree_model.predict(X_test)
dtree_model.score(X_test, y_test)

0.7543333333333333